# Generated by Django 4.2.2 on 2023-06-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequisition',
            name='requisition_Id',
        ),
    ]
